{% set version = "8.5.0" %}
{% set sha256 = "5d06c81504ea961fab709943cf41d8b3e27cdbaae7ccca5baf3f7bb0c5d9f33d" %}

package:
  name: grass
  version: {{ version }}

source:
  url: https://github.com/OSGeo/grass/releases/download/{{ version }}/grass-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/6383-cmake-win.patch
    - patches/7310-remote-decision-using-source-url.patch
    - patches/7376-win-python-home.patch

build:
  number: 0
  missing_dso_whitelist:
    - "*/grass_*.dll"  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}      # [unix]
    - bison          # [unix]
    - cmake
    - flex           # [unix]
    - gettext-tools
    - m2-bison       # [win]
    - m2-flex        # [win]
    - make           # [unix]
    - pkg-config
    - python         # [build_platform != target_platform]
  host:
    - bzip2
    - cairo
    - fftw
    - fontconfig
    - freetype
    - geos
    - gettext       # [osx]
    - libgdal-core
    - libgl-devel   # [linux]
    - libglu        # [linux]
    - libgomp       # [linux]
    - libiconv
    - libpdal-core
    - libpng
    - libpq
    - libsqlite
    - libtiff
    - llvm-openmp   # [osx]
    - openblas
    - pcre          # [win]
    - proj
    - python
    - pywin32       # [win]
    - readline      # [unix]
    - wxpython
    - xorg-libx11   # [linux]
    - zlib
    - zstd
  run:
    - libgomp      # [linux]
    - libopenblas
    - llvm-openmp  # [osx]
    - python
    - pywin32      # [win]
    - wxpython

test:
  commands:
    - grass --version  # [build_platform == target_platform]

about:
  home: https://grass.osgeo.org/
  summary: GRASS computational engine for raster, vector, and geospatial processing
  description: |
    GRASS is a geospatial engine that enables spatial data analysis,
    visualization, and modeling. It provides researchers and practitioners with
    science-backed tools to understand and manage landscapes, natural
    resources, and human environments.
  license: GPL-2.0-or-later
  license_file: COPYING
  doc_url: https://grass.osgeo.org/grass-stable/manuals/
  dev_url: https://github.com/OSGeo/grass

extra:
  recipe-maintainers:
    - HuidaeCho
    - wenzeslaus
